
export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST'
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS'
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE'

export const GET_CATEGORY_SCIENCE_REQUEST = 'GET_CATEGORY_SCIENCE_REQUEST'
export const GET_CATEGORY_SCIENCE_SUCCESS = 'GET_CATEGORY_SCIENCE_SUCCESS'
export const GET_CATEGORY_SCIENCE_FAILURE = 'GET_CATEGORY_SCIENCE_FAILURE'